name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.CITYSPACE_PEM_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan 4.186.60.255 >> ~/.ssh/known_hosts

      - name: Copy files using SCP
        run: |
          scp -o StrictHostKeyChecking=no -r * azureuser@4.186.60.255:CityHousing
